FROM python:3.9

# 종속성 설치
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# 학습 코드 및 데이터 복사
COPY scripts /app/scripts
WORKDIR /app/scripts

# 모델 학습 실행
CMD ["python", "train_model.py"]
