FROM python:3.9-slim

# 최소한의 패키지 설치
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# BentoML 서비스와 모델 복사
COPY app /app

# 작업 디렉토리 설정
WORKDIR /app

# BentoML 서비스 실행
CMD ["bentoml", "serve", "service:svc", "--production"]
